use_frameworks!

target 'UIAnalogClock_Example' do
  pod 'UIAnalogClock', :path => '../'

  target 'UIAnalogClock_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
